import { routeCatalog } from '../../src/routes/routeCatalog.js';

export const ROUTE_MAP_HEADER = '<!-- generated by scripts/generate-route-map.js; do not edit -->';

export const buildRouteMapMarkdown = () => {
  const lines = [
    ROUTE_MAP_HEADER,
    '# Route Map',
    '',
    '| Path | Title | Page Module | Smoke Text |',
    '| --- | --- | --- | --- |',
    ...routeCatalog.map((route) => {
      return `| \`${route.path}\` | ${route.title} | \`${route.pageModule}\` | \`${route.smokeText}\` |`;
    }),
    '',
  ];

  return lines.join('\n');
};
